name: Workflow for master/development branches

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

        # Set up JDK
      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

        # Update Gradle Permission
      - name: Change gradlew Permission
        run: chmod +x gradlew

        # Build App
      - name: Build with Gradle
        run: ./gradlew assemble

        # Upload Built APK
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mifos-passcode
          path: app/build/outputs/apk/debug/